### PR TITLE
[Feature] VectorDrawable icon, Themed / Monochrome icon

### LINKED ISSUE #151: [Feature Request] VectorDrawable Icon - Themed / Monochrome Launcher Icon
- [ ] VectorDrawable Icon
- [ ] Monochrome Icon

I'd like to add these features using a pull request, however, if you're willing to provide the original vector file used to create the app's bitmap icon (if one exists), I would greatly appreciate it, as creating vectors from bitmaps can be quite messy.

-  In combination with the [VectorDrawable Class](https://developer.android.com/reference/android/graphics/drawable/VectorDrawable), apps can use XML vector graphics to render their app icon, which makes scaling the icon's DPI significantly easier while decreasing the icon file size, as it creates the bitmap cache on the fly.

- Starting with [TargetSDK 33 / Android 13](https://developer.android.com/about/versions/13), devices can request an app icon / drawable **vector**'s monochrome version, which can enable the app to render a user-themed / monochromatic version of it's launcher icon:

[Developer Reference Documentation](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

### PR DESCRIPTION
**Pull request by sebastien46**
closes #151

### CODE REVIEW

**Comment by bmx666** [comment]
Hi @sebastien46 
Thanks a lot for your help!
Could you please attach PDF license agreement also?
Is there any reason for reverted commits in PR?

**Comment by bmx666** [comment]
> [Once you obtain any Freepik subscription plan](https://www.freepik.com/profile/preagreement/getstarted/), you will see a link to download a PDF license document every time you download an image from Freepik and Flaticon.
> 
> These licenses will allow you to use our resources without crediting the author and will remain active even when your subscription expires.

Does it contain some sensitive and personal information?
Could you put it into root folder, like LICENSE-ICON.pdf?

**Comment by bmx666** [comment]
I will check behavior on devices from API 23 and let you know

**Comment by bmx666** [comment]
I verified your PR and everything seems fine.
Could you please rewind back your main branch to exclude revert commits and I will merge it into main?

**Comment by sebastien46** [comment]
> I verified your PR and everything seems fine. Could you please rewind back your main branch to exclude revert commits and I will merge it?

I reverted the commit which regenerated the bitmaps, as it didn't really change anything & made the Store icon look worse

> > [Once you obtain any Freepik subscription plan](https://www.freepik.com/profile/preagreement/getstarted/), you will see a link to download a PDF license document every time you download an image from Freepik and Flaticon.
> > These licenses will allow you to use our resources without crediting the author and will remain active even when your subscription expires.
> 
> Does PDF document contain some sensitive and personal information? Could you put it into root folder, like **LICENSE_Freepik_icon.pdf** ?

I used a burner email for my flaticon account, so I wouldn't consider it sensitive information, I'll add it to the root folder

**Comment by bmx666** [comment]
> I used a burner email for my flaticon account, so I wouldn't consider it sensitive information, I'll add it to the root folder

@sebastien46 , could you please create a new PR for license?

**Comment by sebastien46** [comment]
Darn, I was just about to commit the license file right before you merged, gonna have to PR that as well

**Pull request merged**
