### PR TITLE
adding french localization

### PR DESCRIPTION
**Pull request by azgaresncf**
thank you for your app <3
normally everything should be good
it was a very long process though... :')

### CODE REVIEW

**Comment by bmx666** [comment]
Hi @azgaresncf thanks a lot for translation. Please revert the latest default string and squash commits into the first one "adding french localization".

**Comment by azgaresncf** [comment]
> Hi @azgaresncf thanks a lot for translation. Please revert the latest default string and squash commits into the first one "adding french localization".

It should also be good (I'm a noob of git lol)

**Comment by bmx666** [comment]
No problem, just revert the latest string text. It's default resource from Android source. And I will merge your PR.

**Comment by azgaresncf** [comment]
but I've already revert it?

**Comment by bmx666** [comment]
> but I've already revert it?

PR still shows it

**Pull request closed without merging**
