### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
for your [RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2094) (you might have noticed the bot complained about Fastlane being amiss). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build on this; I e.g. strongly recommend moving your screenshots in so they are picked up for your app listing.

### CODE REVIEW

**Comment by IzzySoft** [comment]
PS: Your app identifies with `versionCode: 1` and `versionName: "1.0"` while the tag is named `v0.0.1`. For the build at F-Droid to succeed and auto-update to work, the two should be in sync :wink:

**Comment by bmx666** [comment]
Hi @IzzySoft  thanks for the tips, I'm new in publishing 😅 
I'm preparing "release" version for F-Droid

**Comment by bmx666** [comment]
@IzzySoft I pushed tag v0.0.2 with `versionCode: 2` and `versionName: "0.0.2"`. Are they correct values for F-Droid? I also checked other projects and add free app icon and into fastlane/metadata too.

**Comment by IzzySoft** [comment]
Yes, looks fine, thanks! Closing the PR then as our contributions crossed. Yours are more complete anyway :+1:

**Pull request closed without merging**
