### PR TITLE
Add Translation for Short Desc.

### PR DESCRIPTION
**Pull request by kyoyacchi**

### CODE REVIEW

**Review by bmx666 — APPROVED** [review]

**Comment by bmx666** [comment]
Hi @kyoyacchi , thanks a lot for contribution!

**Comment by kyoyacchi** [comment]
> Hi @kyoyacchi , thanks a lot for contribution!

You are welcome, can you review https://github.com/bmx666/android-appcachecleaner/pull/12 too?

**Comment by bmx666** [comment]
Hi @kyoyacchi sorry it was my mistake, I forgot that F-Droid has limitation on Short Description and their build server return an error now:
`summary` in `tr` should be shorter than 80 characters!

Could you shrink it to 80 characters?

You don't need to create PR for it if you don't want. You can just post shorter version here and I will include into a new commit.

**Comment by kyoyacchi** [comment]
> 

"Erişebilirlik izniyle, yüklü kullanıcı & sistem uyg.larının önbelleğini temizleyin."

How's this?

**Comment by bmx666** [comment]
@kyoyacchi  still 83 characters. 3 more left... 😄

**Comment by kyoyacchi** [comment]
> @kyoyacchi still 83 characters. 3 more left... 😄

"Erişilebilirlik ile yüklü kullanıcı, sistem uyg.larının önbelleğini temizleyin." ?

**Comment by bmx666** [comment]
@kyoyacchi  great! Thanks a lot for quick reply!

**Pull request merged**
