### PR TITLE
New App-Icon 

### PR DESCRIPTION
**Pull request by user0-tb**
A New, moderner App Icon.

### CODE REVIEW

**Comment by bmx666** [comment]
Hi @user0-tb thanks for new icon.

I have a preference for using neutral colors like gray. 
Could you provide information about this icon? Does it have a license? Was it made by you personally, or perhaps modified using other icons?

**Comment by user0-tb** [comment]
The Icon is created with [IconKitchen](Icon.kitchen)

**Comment by OmarNazzal150** [comment]
And also on the new app icon. Add the theme app icon. This would be cool.

**Comment by bmx666** [comment]
Hi @user0-tb

After surveying more than 20 different individuals from various fields and my own surroundings, 100% of them preferred the old icon, no offense. The second icon caused a reaction of something aggressive and audacious, some people considered it an outright hack, without putting a lot of effort into the concept of the icon itself, and therefore most respondents immediately preferred the first one. As a result, the majority of respondents immediately favored the first one. For more than half, the new icon was associated with a paintbrush and painting rather than a broom and cleaning. Some people said such bright colors caused rejection. Some considered the gradient not very appropriate, and couldn't understand the purpose of the dots in the background. In any case, if you have new icons and styles, you are always welcome and I am open to dialogue. In this case, I will leave this PR open.

P.S. next time, be so kind as to conduct a statistical social survey yourself and adjust your preferences, listening to constructive criticism.
P.S.2 I myself spent more than 2 months searching for this icon, polling my surroundings and presenting various options. This option was the most optimal of the 50 respondents.

**Pull request closed without merging**
